export const PERSONAL_INFO = {
  name: "Anurag Verma",
  role: "UI/UX Designer & Design Engineer",
  experienceYears: "2+",
  email: "anuragverma.dd@gmail.com",
  phone: "+91 7278963186",
  location: "Kolkata, India",
  timezone: "Asia/Kolkata",
  status: "Available for Projects",
  availabilityPeriod: "March 2026",
  bio: "UI/UX Designer and Design Engineer crafting thoughtful digital products, robust design systems, and fluid frontend interactions. Experienced across complex SaaS workflows, AI-assisted design tooling, and conversion-driven experiences.",
  stats: [
    { value: "2+", label: "Years Crafting Digital Products", highlight: "End-to-end design & frontend" },
    { value: "30%", label: "Faster Research & Ideation", highlight: "AI-assisted workflows at Fortmindz" },
    { value: "25%", label: "Component Reuse Growth", highlight: "Design system leadership at Esolz" },
    { value: "10%", label: "Reduction in User Errors", highlight: "Complex UX flow optimization" },
  ],
  socials: {
    linkedin: "https://www.linkedin.com/in/vermanurag/",
    dribbble: "https://dribbble.com/ux_anurag",
    figma: "https://www.figma.com/@ux_anurag",
    peerlist: "https://peerlist.io/anurag_verma",
    medium: "https://medium.com/@anurag_verma",
  },
};

export const NAV_ITEMS = [
  { label: "About", href: "/about" },
  { label: "Projects", href: "/projects" },
  { label: "Side Quests", href: "/#side-quests" },
  { label: "Contact", href: "/contact" },
];

export const SKILLS_DATA = {
  designTools: [
    { name: "Figma", level: "Expert", desc: "Design systems, auto-layout, variables & interactive prototyping" },
    { name: "FigJam", level: "Advanced", desc: "User flows, journey mapping & workshop synthesis" },
    { name: "Adobe XD", level: "Proficient", desc: "Vector UI layouts & legacy system handoffs" },
    { name: "Miro", level: "Proficient", desc: "Collaborative ideation & remote discovery sessions" },
    { name: "Photopea", level: "Proficient", desc: "Asset optimization, raster work & visual polish" },
  ],
  aiTools: [
    { name: "ChatGPT", role: "UX Writing & Logic", tag: "Research & Copy" },
    { name: "Claude AI", role: "Heuristic Analysis & IA", tag: "Synthesis & Flow" },
    { name: "Figma AI", role: "Layout & Wireframe Acceleration", tag: "Rapid Prototyping" },
    { name: "Google Stitch", role: "Interface Generation", tag: "Exploration" },
    { name: "Perplexity", role: "Competitor Intelligence", tag: "Deep Discovery" },
    { name: "Gemini", role: "Multimodal Synthesis", tag: "Workflow Design" },
  ],
  designSkills: [
    "User Research & Interviews",
    "Wireframing & Information Architecture",
    "Rapid & Interactive Prototyping",
    "Design Systems & Token Architecture",
    "Micro-Interactions & Motion Design",
    "Responsive Design (Mobile to 4K)",
    "WCAG 2.1 AA/AAA Accessibility",
    "Design Thinking & User-Centered Design",
  ],
  frontendSkills: [
    "Next.js 15 & React 19",
    "TypeScript (Strict)",
    "Tailwind CSS v4 & CSS Tokens",
    "GSAP & ScrollTrigger Choreography",
    "Lenis Smooth Scrolling",
    "Motion (Framer Motion API)",
    "Three.js / React Three Fiber",
  ],
};

export const MILESTONES_DATA = [
  {
    id: "fortmindz",
    title: "UI/UX Designer",
    company: "Fortmindz Private Limited",
    period: "Jan 2026 – Present",
    type: "Work",
    featured: true,
    location: "Kolkata, WB (Remote)",
    description: "Designing end-to-end responsive experiences for web applications and mobile apps. Pioneer AI tool integrations (ChatGPT, Claude, Figma AI, Google Stitch) reducing early-stage discovery by ~30% and prototype cycles by ~25%.",
    metrics: ["-30% Discovery Time", "-25% Prototyping Speed", "Figma AI Workflow"],
    badge: "Current Role",
  },
  {
    id: "esolz",
    title: "UI/UX Designer",
    company: "Esolz Technologies",
    period: "May 2024 – Aug 2025",
    type: "Work",
    featured: true,
    location: "Kolkata, WB",
    description: "Owned design delivery from initial concept to high-fidelity handoff. Built centralized design system increasing cross-platform component reuse by 25%. Streamlined complex multi-step workflows reducing user input errors by 10%.",
    metrics: ["+25% Component Reuse", "-10% User Errors", "-5 Days Cycle Time"],
    badge: "Design Systems",
  },
  {
    id: "certifications-2023",
    title: "UI/UX Specialization Certification",
    company: "Internshala & Industry Mentors",
    period: "May 2023 – Oct 2023",
    type: "Achievement",
    featured: false,
    location: "Remote",
    description: "Comprehensive intensive training in user research methodologies, heuristic evaluation, design system governance, and WCAG accessibility standards.",
    metrics: ["Design Thinking", "WCAG Standards", "Heuristic Audits"],
    badge: "Certification",
  },
  {
    id: "ioteraction",
    title: "UI/UX Design Intern",
    company: "Ioteraction Technologies Services",
    period: "Sept 2021 – Mar 2022",
    type: "Work",
    featured: false,
    location: "Remote",
    description: "Collaborated in early-stage concept visualization and collaborative ideation using Miro. Developed foundational design system components that reduced design QA review cycles by 5%.",
    metrics: ["Design System Starter", "-5% QA Review Time"],
    badge: "First Product Role",
  },
  {
    id: "degree",
    title: "B.Com (Hons.) in Accountancy & Finance",
    company: "The Bhawanipur Education Society College",
    period: "2017 – 2020",
    type: "Education",
    featured: false,
    location: "Kolkata, WB",
    description: "Graduated with honors. Developed rigorous analytical thinking, numerical intuition, and business acumen that directly informs data-dense SaaS and fintech UX.",
    metrics: ["Analytical Rigor", "Fintech UX Foundation"],
    badge: "Education",
  },
];

export const SERVICES_DATA = [
  {
    num: "01",
    title: "Product & UI/UX Design",
    description: "From ambiguous requirements to intuitive digital experiences. I map user journeys, design low-friction interaction models, and deliver production-ready Figma files with meticulous edge-case handling.",
    deliverables: ["User Research & Journey Mapping", "Wireframes & Information Architecture", "High-Fidelity UI & Interactive Prototypes", "Developer Handoff Documentation"],
  },
  {
    num: "02",
    title: "Design Systems & Tokens",
    description: "Scalable component libraries built with Figma variables and mirrored directly into CSS custom properties. Ensuring consistency across digital platforms while cutting sprint cycles.",
    deliverables: ["Atomic Component Architecture", "Multi-Tier Token Systems (Light/Dark)", "Figma Variables & Auto-Layout 5.0", "Living Styleguides & Governance"],
  },
  {
    num: "03",
    title: "Design Engineering & Motion",
    description: "Bridging the gap between Figma and the browser. Implementing bespoke micro-interactions, smooth scroll storytelling, and responsive layouts that perform flawlessly at 60fps.",
    deliverables: ["Next.js & React Frontend Integration", "GSAP & Motion Micro-Interactions", "Lenis Smooth Scroll Sync", "Responsive Multi-Breakpoint Polish"],
  },
  {
    num: "04",
    title: "AI-Accelerated UX Strategy",
    description: "Deploying next-gen AI design tools to compress discovery, synthesize user research, generate rapid layout variations, and refine product microcopy with measurable business velocity.",
    deliverables: ["AI Workflow Integration", "Rapid Generative Wireframing", "UX Copywriting & Content Strategy", "Competitor Benchmark Synthesis"],
  },
];

export const PROCESS_STEPS = [
  {
    step: "01",
    title: "Discover & Deconstruct",
    subtitle: "Understanding the problem before drawing a single line.",
    description: "We dive deep into stakeholder goals, user frustrations, and technical constraints. Using AI-assisted synthesis and competitor benchmarking, we extract the core friction points to define clear design criteria.",
  },
  {
    step: "02",
    title: "Architect & Wireframe",
    subtitle: "Structuring content for effortless mental models.",
    description: "Creating low-fidelity wireframes, user flow diagrams, and information hierarchies. We test structural hypotheses early to ensure the fundamental user journey is intuitive before visual styling begins.",
  },
  {
    step: "03",
    title: "Craft & Systematize",
    subtitle: "High-fidelity visual design grounded in systematic tokens.",
    description: "Applying typography, purposeful color ramps, and tactile component states in Figma. Every component is tokenized and prepared for seamless handoff with responsive auto-layouts and accessibility checks.",
  },
  {
    step: "04",
    title: "Code, Animate & Refine",
    subtitle: "Bringing the design into the browser with precision motion.",
    description: "Translating static frames into production-ready web interfaces with Next.js, Tailwind v4, Motion, and GSAP. Fine-tuning easing curves, verifying WCAG compliance, and ensuring snappy performance.",
  },
];

export const NOTES_ARTICLES = [
  {
    slug: "ai-in-ux-research",
    title: "Integrating AI in UX Research: Cutting Early-Stage Design Time by 30%",
    publication: "Medium",
    url: "https://medium.com/@anurag_verma",
    date: "Feb 2026",
    readTime: "5 min read",
    tag: "AI & Methodology",
    excerpt: "How generative models and structured prompting can accelerate competitor analysis, heuristic audits, and user flow ideation without sacrificing designer empathy.",
  },
  {
    slug: "design-systems-tokens",
    title: "Building Scalable Design Systems: From Figma Variables to CSS Tokens",
    publication: "Medium",
    url: "https://medium.com/@anurag_verma",
    date: "Nov 2025",
    readTime: "7 min read",
    tag: "Design Systems",
    excerpt: "A practical guide to structuring three-tier token hierarchies that empower engineers to ship faster while keeping brand consistency across enterprise apps.",
  },
  {
    slug: "design-engineer-bridge",
    title: "The Rise of the Design Engineer: Bridging the Figma-Code Chasm",
    publication: "Medium",
    url: "https://medium.com/@anurag_verma",
    date: "Aug 2025",
    readTime: "6 min read",
    tag: "Engineering",
    excerpt: "Why understanding DOM constraints, CSS variable mechanics, and motion choreography transforms a good UI designer into an invaluable product partner.",
  },
];

export const TESTIMONIALS_DATA = [
  {
    quote: "Anurag has an exceptional eye for micro-interactions and layout balance. He doesn't just hand off static Figma mockups—he thinks through edge cases, responsive states, and actual user behavior.",
    author: "Debojyoti Ghosh",
    role: "Senior Engineering Lead",
    company: "Fortmindz Private Limited",
    badge: "Verified Collaborator",
    avatar: "DG",
  },
  {
    quote: "His work on our design system streamlined cross-team handoffs and measurably sped up our feature delivery. Anurag's combination of design instinct and technical awareness is rare.",
    author: "Sayan Bhattacharya",
    role: "Project Manager",
    company: "Esolz Technologies",
    badge: "Verified Client",
    avatar: "SB",
  },
  {
    quote: "Fast, communicative, and detail-oriented. Anurag delivered an intuitive SaaS interface that helped us reduce user onboarding questions and improve our trial conversion rate.",
    author: "Rohan Mukherjee",
    role: "Product Founder",
    company: "FinFlow Analytics",
    badge: "Verified Client",
    avatar: "RM",
  },
];

export const CASE_STUDIES = [
  {
    slug: "finflow-saas-analytics",
    title: "FinFlow — Real-Time Financial Intelligence",
    tagline: "Simplifying complex multi-asset financial workflows for high-growth modern teams.",
    role: "Lead UI/UX Designer & Prototyper",
    company: "Fortmindz",
    year: "2026",
    category: "Fintech SaaS",
    services: ["User Research", "Design System", "Interactive Prototyping"],
    metrics: [
      { label: "Time-to-Insight", value: "-35%" },
      { label: "Task Completion", value: "98.4%" },
      { label: "User Satisfaction", value: "4.9/5" },
    ],
    liveUrl: "https://dribbble.com/ux_anurag",
    thumbnail: "/projects/finflow.jpg",
    accentColor: "#E95810",
    summary: "FinFlow transformed a fragmented multi-account financial reporting system into an intuitive, real-time dashboard. By conducting rigorous user journey mapping and implementing modular widget architecture, we reduced user cognitive load and sped up executive reporting.",
    problem: "Enterprise financial managers were juggling three disparate tools to monitor liquidity, cash flow velocity, and runway projections. Information was siloed in 20+ column spreadsheets with high error rates.",
    solution: "We engineered a centralized command center featuring custom data visualization cards, predictive cash runway charts, and natural-language query filters. The interface respects WCAG AA standards with custom tabular numeric formatting.",
  },
  {
    slug: "nexus-design-system",
    title: "Nexus — Enterprise Design System Architecture",
    tagline: "A unified, accessible tokenized design system spanning web, iOS, and Android platforms.",
    role: "Design System Architect",
    company: "Esolz Technologies",
    year: "2025",
    category: "Design System",
    services: ["Design Tokens", "Component Library", "Documentation", "Figma Governance"],
    metrics: [
      { label: "Component Reuse", value: "+25%" },
      { label: "Handoff Time", value: "-5 Days" },
      { label: "WCAG Compliance", value: "100% AA" },
    ],
    liveUrl: "https://dribbble.com/ux_anurag",
    thumbnail: "/projects/nexus.jpg",
    accentColor: "#E95810",
    summary: "Nexus unified four siloed product teams under a single, cohesive visual language. Featuring over 240 tokenized components with full dark and light mode support, Nexus transformed sprint handoffs into a plug-and-play process.",
    problem: "The company's digital products suffered from visual inconsistency, duplicated engineering effort, and accessibility gaps due to lack of a centralized component repository.",
    solution: "We built a multi-tier token hierarchy using Figma Variables and synchronized it directly to Tailwind CSS variables. The system included strict component documentation, interactive states, and automated contrast checkers.",
  },
  {
    slug: "creativestudio-ai-prototyper",
    title: "StudioAI — Generative UX Prototyping Canvas",
    tagline: "Empowering product designers to generate and iterate on responsive wireframes in seconds.",
    role: "Product Designer & Frontend Engineer",
    company: "Independent / Exploration",
    year: "2026",
    category: "AI Tooling",
    services: ["Interface Design", "Prompt UX", "Design Engineering"],
    metrics: [
      { label: "Wireframe Speed", value: "4x Faster" },
      { label: "Design Exploration", value: "-30% Time" },
      { label: "Early Concept Iteration", value: "25%+" },
    ],
    liveUrl: "https://peerlist.io/anurag_verma",
    thumbnail: "/projects/studioai.jpg",
    accentColor: "#A3CC42",
    summary: "StudioAI is an exploratory canvas interface that couples natural-language intent with component-level layout generation, allowing designers to rapidly explore variations without starting from a blank page.",
    problem: "Early-stage UX concepting is often bottlenecked by manual repetitive wireframing of standard patterns (navbars, grids, auth flows, checkout steps), reducing time spent on deep user problems.",
    solution: "We designed a multi-modal canvas where designers can write prompt commands or drop sketches to generate editable Figma-ready components with real typography and auto-layout rules.",
  },
  {
    slug: "carepulse-telehealth",
    title: "CarePulse — Seamless Patient Telemedicine",
    tagline: "Frictionless doctor consultations, medical history tracking, and appointment scheduling.",
    role: "Senior UI/UX Designer",
    company: "Fortmindz",
    year: "2025",
    category: "HealthTech",
    services: ["Mobile App UX", "Accessibility", "Design System"],
    metrics: [
      { label: "Booking Drop-Off", value: "-12%" },
      { label: "Patient Onboarding", value: "< 2 mins" },
      { label: "Accessibility Score", value: "AAA Contrast" },
    ],
    liveUrl: "https://dribbble.com/ux_anurag",
    thumbnail: "/projects/carepulse.jpg",
    accentColor: "#E95810",
    summary: "CarePulse delivers a calm, empathetic healthcare interface designed for all ages. With simplified symptom triage, one-tap booking, and instant video consults, CarePulse minimized user anxiety during critical moments.",
    problem: "Existing telehealth apps overwhelmed patients with cluttered clinical jargon, complex booking calendars, and confusing insurance validation steps.",
    solution: "We reorganized the booking architecture into a 3-step progressive disclosure flow with high-contrast text, clear status badges, and instant appointment reminders.",
  },
];
